### PR TITLE
Small fix to avoid MNU

### PR DESCRIPTION
**Pull request by bpieber**
Cuis insisted on the formatting changes. Sorry about that.

### CODE REVIEW

**Comment by dtlewis290** [comment]
Hi Bernard, the fix is "anEnvironmentDictionary keysAndValuesDo: [:k :v | envArray add: (k, '=', v) asByteArray].", is that right?

**Comment by bpieber** [comment]
> Hi Bernard, the fix is "anEnvironmentDictionary keysAndValuesDo: [:k :v | envArray add: (k, '=', v) asByteArray].", is that right?

Yes, that change avoided a MNU. There is probably a much better fix, though.

**Comment by dtlewis290** [comment]
Thank you Bernhard, I committed your fix. I committed it directly rather than doing a merge just to avoid the formatting changes. Thanks a lot for fixing this and I am sorry it took me so long to merge it.

**Comment by bpieber** [comment]
Thanks for committing my fix. I wonder how to avoid the formatting differences in the future. How do you create the package file? I assume yon't you export it from a Cuis image? Because if you did, you'd have the same formatting, right?

**Comment by bpieber** [comment]
Hi David, thank you for committing the fix.

**Comment by dtlewis290** [comment]
Hi Bernhard,

>> I wonder how to avoid the formatting differences in the future. How do
you create the package file?
>> I assume yon't you export it from a Cuis image? Because if you did,
you'd have the same formatting, right?

For small things, I just use fileouts or copy/paste to go back and forth
between Cuis and Squeak.
The master source is in Monticello format on the squeaksource.com
repository, so when I am ready to commit to Cuis git, I do this:
1) File out the OSProcess packages from Squeak
2) Use /usr/bin/tr and /usr/bin/sed to convert line endings and assignment
characters
3) In Cuis, file the packages in
4) Save the package from Cuis
5) Check the git diffs and then commit the updated Cuis package

Dave

**Pull request closed without merging**
